"""add event_config_id to webhook_logs

Revision ID: 2d6062fe42ac
Revises: 36e805ba42a3
Create Date: 2026-07-09 15:54:37.019201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6062fe42ac'
down_revision: Union[str, None] = '36e805ba42a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_logs', sa.Column('event_config_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_webhook_logs_event_config_id'), 'webhook_logs', ['event_config_id'], unique=False)
    op.create_foreign_key('fk_webhook_logs_event_config_id_event_configs', 'webhook_logs', 'event_configs', ['event_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_webhook_logs_event_config_id_event_configs', 'webhook_logs', type_='foreignkey')
    op.drop_index(op.f('ix_webhook_logs_event_config_id'), table_name='webhook_logs')
    op.drop_column('webhook_logs', 'event_config_id')
    # ### end Alembic commands ###
