"""any_message

Revision ID: 36e805ba42a3
Revises: 
Create Date: 2026-07-09 15:37:00.114596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


webhook_status_enum = postgresql.ENUM(
    'PENDING', 'SUCCESS', 'FAILED', name='webhookstatus', create_type=False
)

# revision identifiers, used by Alembic.
revision: str = '36e805ba42a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    webhook_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_secret', sa.String(length=255), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_project_company_name')
    )
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_hashed_secret'), 'projects', ['hashed_secret'], unique=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_active'), 'projects', ['is_active'], unique=False)
    op.create_table('event_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'event_type', name='uq_event_config_project_event')
    )
    op.create_index(op.f('ix_event_configs_event_type'), 'event_configs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_configs_id'), 'event_configs', ['id'], unique=False)
    op.create_index(op.f('ix_event_configs_project_id'), 'event_configs', ['project_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('event_config_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_config_id'], ['event_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_webhook_events_event_config_id'), 'webhook_events', ['event_config_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_project_id'), 'webhook_events', ['project_id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=True),
    sa.Column('status', webhook_status_enum, nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['webhook_events.event_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_event_id'), 'webhook_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_response_code'), 'webhook_logs', ['response_code'], unique=False)
    op.create_index(op.f('ix_webhook_logs_retry_count'), 'webhook_logs', ['retry_count'], unique=False)
    op.create_index(op.f('ix_webhook_logs_status'), 'webhook_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_status'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_retry_count'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_response_code'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_webhook_events_project_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_config_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_event_configs_project_id'), table_name='event_configs')
    op.drop_index(op.f('ix_event_configs_id'), table_name='event_configs')
    op.drop_index(op.f('ix_event_configs_event_type'), table_name='event_configs')
    op.drop_table('event_configs')
    op.drop_index(op.f('ix_projects_is_active'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_hashed_secret'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    webhook_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
