"""any_message

Revision ID: 3ba4b69e3dd0
Revises: 65e65b53e8cc
Create Date: 2026-07-14 11:08:10.490530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba4b69e3dd0'
down_revision: Union[str, None] = '65e65b53e8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_logs', sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('webhook_logs', sa.Column('incoming_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('webhook_logs', sa.Column('forwarding_target_url', sa.Text(), nullable=True))
    op.add_column('webhook_logs', sa.Column('target_response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('webhook_logs', sa.Column('processing_duration_ms', sa.Integer(), nullable=True))
    op.add_column('webhook_logs', sa.Column('source_ip', sa.String(length=64), nullable=True))
    op.add_column('webhook_logs', sa.Column('http_method', sa.String(length=16), nullable=True))
    op.alter_column('webhook_logs', 'event_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_constraint('webhook_logs_event_id_fkey', 'webhook_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('webhook_logs_event_id_fkey', 'webhook_logs', 'webhook_events', ['event_id'], ['event_id'], ondelete='SET NULL')
    op.alter_column('webhook_logs', 'event_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('webhook_logs', 'http_method')
    op.drop_column('webhook_logs', 'source_ip')
    op.drop_column('webhook_logs', 'processing_duration_ms')
    op.drop_column('webhook_logs', 'target_response_headers')
    op.drop_column('webhook_logs', 'forwarding_target_url')
    op.drop_column('webhook_logs', 'incoming_headers')
    op.drop_column('webhook_logs', 'request_payload')
    # ### end Alembic commands ###
