"""new colom add in event



Revision ID: 3d67030093b7
Revises: af8e4e5bef13
Create Date: 2026-07-14 17:57:54.371536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d67030093b7'
down_revision: Union[str, None] = 'af8e4e5bef13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_configs', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_event_configs_is_active'), 'event_configs', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_configs_is_active'), table_name='event_configs')
    op.drop_column('event_configs', 'is_active')
    # ### end Alembic commands ###
