"""any_message

Revision ID: 65e65b53e8cc
Revises: bc7a04cdabbc
Create Date: 2026-07-09 17:24:06.190438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e65b53e8cc'
down_revision: Union[str, None] = 'bc7a04cdabbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_logs', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.drop_index('ix_webhook_logs_retry_count', table_name='webhook_logs')
    op.create_index(op.f('ix_webhook_logs_attempt_number'), 'webhook_logs', ['attempt_number'], unique=False)
    op.drop_column('webhook_logs', 'retry_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_logs', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_webhook_logs_attempt_number'), table_name='webhook_logs')
    op.create_index('ix_webhook_logs_retry_count', 'webhook_logs', ['retry_count'], unique=False)
    op.drop_column('webhook_logs', 'attempt_number')
    # ### end Alembic commands ###
