"""any_message

Revision ID: b9d2a118191e
Revises: 4b9a2f1c7d8a
Create Date: 2026-07-16 17:01:22.817304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9d2a118191e'
down_revision: Union[str, None] = '4b9a2f1c7d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('webhook_events', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("""
        UPDATE webhook_events
        SET payload = COALESCE(CAST(request_payload AS jsonb), '{}'::jsonb)
        WHERE payload IS NULL
    """)
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('webhook_events', 'target_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.execute("""
        UPDATE webhook_logs
        SET event_id = NULL
        WHERE event_id IS NOT NULL
          AND NOT EXISTS (
              SELECT 1
              FROM webhook_events AS we
              WHERE we.event_id = webhook_logs.event_id
          )
    """)
    op.drop_column('webhook_events', 'request_payload')
    op.create_foreign_key('webhook_logs_event_id_fkey', 'webhook_logs', 'webhook_events', ['event_id'], ['event_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_logs', type_='foreignkey')
    op.add_column('webhook_events', sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('webhook_events', 'target_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('webhook_events', 'metadata_json')
    op.drop_column('webhook_events', 'payload')
    # ### end Alembic commands ###
