"""ok

Revision ID: c51a7d67c9bc
Revises: b9d2a118191e
Create Date: 2026-07-17 12:17:17.456875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c51a7d67c9bc'
down_revision: Union[str, None] = 'b9d2a118191e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.drop_column('webhook_logs', 'forwarding_target_url')
    op.drop_column('webhook_logs', 'response_body')
    op.drop_column('webhook_logs', 'request_payload')
    op.drop_column('webhook_logs', 'incoming_headers')
    op.drop_column('webhook_logs', 'target_response_headers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_logs', sa.Column('target_response_headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('webhook_logs', sa.Column('incoming_headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('webhook_logs', sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('webhook_logs', sa.Column('response_body', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('webhook_logs', sa.Column('forwarding_target_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_column('companies', 'is_active')
    # ### end Alembic commands ###
