"""add_missing_event_config_fields

Revision ID: fcf63a16eacc
Revises: c51a7d67c9bc
Create Date: 2026-07-21 11:19:57.130020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcf63a16eacc'
down_revision: Union[str, None] = 'c51a7d67c9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_configs', sa.Column('retention_days', sa.Integer(), nullable=True))
    op.add_column('event_configs', sa.Column('delete_time', sa.String(length=16), nullable=True))
    op.add_column('event_configs', sa.Column('payload_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('event_configs', sa.Column('payload_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_configs', 'payload_types')
    op.drop_column('event_configs', 'payload_keys')
    op.drop_column('event_configs', 'delete_time')
    op.drop_column('event_configs', 'retention_days')
    # ### end Alembic commands ###
